# VS code's cody AI has been used to generate the comments in this file, No other
# aspects of the file have been generated by AI, Have fun!


class ChessPiece: # basse class for all chess pieces
    def __init__(self, color, name): 
        self.color = color
        self.name = name

    def __str__(self): # returns the first letter of the piece name
        return self.name[0].upper() if self.color == 'white' else self.name[0].lower()


class ChessBoard: # class for the chess board
    def __init__(self): 
        self.board = self.create_board()

    def create_board(self): # creates the board
        
        board = [[None] * 8 for _ in range(8)] # create an 8x8 board

        for i in range(8): 
            board[1][i] = ChessPiece('white', 'pawn') # place pawns
            board[6][i] = ChessPiece('black', 'pawn') # place pawns
        pieces = ['rook', 'knight', 'bishop', 'queen', 'king', 'bishop', 'knight', 'rook'] # place other pieces
        for i, piece in enumerate(pieces): # place pieces
            board[0][i] = ChessPiece('white', piece)
            board[7][i] = ChessPiece('black', piece)
        return board

    def display(self): # displays the board
        
        for row in self.board: # for each row in the board
            print(" | ".join(str(piece) if piece else '.' for piece in row)) # print each row
            print("-" * 33) # print the divider

    def move_piece(self, start, end): # moves the piece depending on the user input
        
        start_row, start_col = start # unpacking the start and end coordinates
        